name: Restart Codespace
on:
  repository_dispatch:
    types: [restart-codespace]
jobs:
  restart:
    runs-on: ubuntu-latest
    steps:
      - name: Install GitHub CLI
        run: |
          sudo apt-get update
          sudo apt-get install -y gh
      - name: Authenticate GitHub CLI
        run: |
          echo "Using default GitHub Actions token for authentication..."
          gh auth setup-git
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Restart Codespace
        env:
          CODESPACE_NAME: ${{ github.event.client_payload.codespace_name }}
        run: |
          echo "Waiting 60 seconds to ensure stop completes..."
          sleep 60
          echo "Attempting to restart Codespace $CODESPACE_NAME..."
          gh api -X POST \
            -H "Accept: application/vnd.github.v3+json" \
            /user/codespaces/$CODESPACE_NAME/start \
            || echo "Failed to restart Codespace; it may already be running or inaccessible."
