name: Restart Codespace
on:
  repository_dispatch:
    types: [restart-codespace]
jobs:
  restart:
    runs-on: ubuntu-latest
    steps:
      - name: Install GitHub CLI
        run: |
          sudo apt-get update
          sudo apt-get install -y gh
      - name: Restart Codespace
        env:
          CODESPACE_NAME: ${{ github.event.client_payload.codespace_name }}
        run: |
          echo "Waiting 60 seconds to ensure stop completes..."
          sleep 60
          echo "Restarting Codespace $CODESPACE_NAME..."
          gh codespace code -c "$CODESPACE_NAME" || echo "Restart initiated; session may not connect from workflow."
