name: Restart Codespace
on:
  repository_dispatch:
    types: [restart-codespace]
jobs:
  restart:
    runs-on: ubuntu-latest
    steps:
      - name: Install GitHub CLI and SSH Tools
        run: |
          sudo apt-get update
          sudo apt-get install -y gh openssh-client
          echo "GitHub CLI version:"
          gh --version
      - name: Authenticate GitHub CLI
        run: |
          echo "Authenticating with PAT..."
          echo "${{ secrets.CODESPACE_PAT }}" | gh auth login --with-token
          gh auth status
      - name: Set Up SSH Keys
        run: |
          echo "Generating SSH key for GitHub CLI..."
          mkdir -p ~/.ssh
          ssh-keygen -t ed25519 -C "github-actions@gofly" -f ~/.ssh/id_ed25519 -N "" || { echo "SSH key generation failed"; exit 1; }
          echo "Adding SSH key to GitHub..."
          gh ssh-key add ~/.ssh/id_ed25519.pub --title "GitHub Actions SSH Key" --type authentication || { echo "Failed to add SSH key"; exit 1; }
          echo "Configuring SSH..."
          echo "Host github.com" >> ~/.ssh/config
          echo "  HostName github.com" >> ~/.ssh/config
          echo "  User git" >> ~/.ssh/config
          echo "  IdentityFile ~/.ssh/id_ed25519" >> ~/.ssh/config
          chmod 600 ~/.ssh/id_ed25519
          chmod 644 ~/.ssh/id_ed25519.pub
          eval "$(ssh-agent -s)"
          ssh-add ~/.ssh/id_ed25519 || { echo "Failed to add SSH key to agent"; exit 1; }
          echo "SSH keys configured successfully."
      - name: Restart Codespace
        env:
          CODESPACE_NAME: ${{ github.event.client_payload.codespace_name }}
        run: |
          echo "Waiting 120 seconds to ensure stop completes..."
          sleep 120
          echo "Attempting to restart Codespace $CODESPACE_NAME..."
          RETRY_COUNT=0
          MAX_RETRIES=3
          until [ $RETRY_COUNT -ge $MAX_RETRIES ]; do
            START_OUTPUT=$(gh api -X POST \
              -H "Accept: application/vnd.github.v3+json" \
              /user/codespaces/$CODESPACE_NAME/start 2>&1)
            START_STATUS=$?
            if [ $START_STATUS -eq 0 ]; then
              echo "Codespace $CODESPACE_NAME restart initiated successfully."
              exit 0
            fi
            echo "Failed to restart Codespace $CODESPACE_NAME (Attempt $((RETRY_COUNT + 1))/$MAX_RETRIES)."
            echo "Error details: $START_OUTPUT"
            if echo "$START_OUTPUT" | grep -q "HTTP 409"; then
              echo "Conflict detected (HTTP 409). Retrying in 30 seconds..."
              sleep 30
            else
              echo "Non-retryable error. Exiting."
              exit 1
            fi
            RETRY_COUNT=$((RETRY_COUNT + 1))
          done
          echo "Failed to restart Codespace $CODESPACE_NAME after $MAX_RETRIES attempts."
          exit 1
      - name: Wake Up Codespace
        env:
          CODESPACE_NAME: ${{ github.event.client_payload.codespace_name }}
        run: |
          echo "Waiting 180 seconds for Codespace to stabilize..."
          sleep 180
          echo "Checking SSH agent status..."
          ssh-add -l || echo "No SSH keys loaded in agent."
          echo "Attempting to SSH into Codespace $CODESPACE_NAME to trigger initialization..."
          RETRY_COUNT=0
          MAX_RETRIES=5
          until [ $RETRY_COUNT -ge $MAX_RETRIES ]; do
            echo "Attempt $((RETRY_COUNT + 1)): Running gh codespace ssh with debug..."
            # Run gh command in a subshell to capture all output
            SSH_OUTPUT=$(bash -c "gh codespace ssh -c $CODESPACE_NAME --debug -- whoami 2>&1")
            SSH_STATUS=$?
            if [ $SSH_STATUS -eq 0 ]; then
              echo "Successfully connected to Codespace $CODESPACE_NAME via SSH."
              echo "Checking if port 6200 is listening..."
              NC_OUTPUT=$(gh codespace ssh -c $CODESPACE_NAME -- sh -c "nc -z localhost 6200 && echo 'Port 6200 is listening'" 2>&1)
              NC_STATUS=$?
              if [ $NC_STATUS -eq 0 ]; then
                echo "Confirmed port 6200 is listening in Codespace $CODESPACE_NAME."
                break
              else
                echo "Failed to confirm port 6200 is listening. Error details: $NC_OUTPUT"
              fi
            else
              echo "Failed to SSH into Codespace $CODESPACE_NAME (Attempt $((RETRY_COUNT + 1))/$MAX_RETRIES)."
              echo "Error details: $SSH_OUTPUT"
            fi
            echo "Retrying in 30 seconds..."
            sleep 30
            RETRY_COUNT=$((RETRY_COUNT + 1))
          done
          if [ $RETRY_COUNT -ge $MAX_RETRIES ]; then
            echo "Warning: Failed to SSH into Codespace $CODESPACE_NAME after $MAX_RETRIES attempts. Port forwarding may not be initialized."
          fi
